export const NavigationString = {
    HOME: 'HOME',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    FORGETPASSWARD: 'FORGETPASSWARD',
    SETPASSWARD: 'SETPASSWARD',
    COOSEACCOUNT: 'CHOOSEACCOUNT',
    BOOKING:'BOOKING',
    PROFILE:'PROFILE',
    BOTTOMTAB:'BOTTOMTAB',
    MYCARD:'MYCARD'


}
